### ISSUE TITLE
How reset

### ISSUE THREAD

**Issue by hejsiri** [curla92/LED-Dimmer-Homekit#1]
Hello

How reset to default HomeKit ID and WiFi settings?

**Comment by curla92** [comment]
First minute after reboot, toggle 10 times quickly show setup in eve app.

**Comment by hejsiri** [comment]
Only EVE app ? Does the HOME app also work? JJust turn on / off 10 times within the first minute of starting?

**Comment by curla92** [comment]
whats your version installed?

**Comment by hejsiri** [comment]
2.2.1

**Comment by hejsiri** [comment]
And can you add the next version of the HomeKit ID reset option to make it available in the EVE application? Or one option to restore to factory settings (wifi and Homekid id).

**Comment by curla92** [comment]
homekit id reset is already available . you must switch 10 times show setup in eve app first minute.

**Comment by hejsiri** [comment]
OK thx :)

**Comment by hejsiri** [comment]
Unfortunately, but when I tried to add I had an error. The accessory failed. Attempting to add again shows the message that the accessory is already added. How to reset HomeKit ID if the device is not visible and I cannot switch the "show setup" option in EVE?

**Comment by curla92** [comment]
> Unfortunately, but when I tried to add I had an error. The accessory failed. Attempting to add again shows the message that the accessory is already added. How to reset HomeKit ID if the device is not visible and I cannot switch the "show setup" option in EVE?

Only the last version has the hard reset with toggling button. You must to re flash your dispositive and install the last version.
